input {
  file {
    path => "/sample-logs/auth.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    mode => "read"
    type => "linux-auth"
  }
}

filter {
  grok {
    match => {
      "message" => [
        "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:host} sshd\[%{NUMBER:pid}\]: Failed password for invalid user %{USERNAME:target_user} from %{IP:source_ip} port %{NUMBER:source_port} ssh2",
        "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:host} sshd\[%{NUMBER:pid}\]: Failed password for %{USERNAME:target_user} from %{IP:source_ip} port %{NUMBER:source_port} ssh2",
        "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:host} sudo: %{USERNAME:user} : TTY=%{DATA:tty} ; PWD=%{DATA:pwd} ; USER=%{USERNAME:run_as_user} ; COMMAND=%{GREEDYDATA:command}",
        "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:host} %{DATA:program}\[%{NUMBER:pid}\]: %{GREEDYDATA:event_detail}"
      ]
    }
  }

  if "Failed password" in [message] {
    mutate { add_field => { "event_type" => "failed_ssh_login" } }
  } else if "sudo:" in [message] {
    mutate { add_field => { "event_type" => "privilege_escalation" } }
  } else {
    mutate { add_field => { "event_type" => "general_security_event" } }
  }

  date {
    match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "security-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
